In [1]:
import pandas as pd

In [3]:
sample_test_out = pd.read_csv('sample_test_out.csv')

In [5]:
sample_test_out.head(5)

   sample_id      price
0     217392  62.080008
1     209156  17.189763
2     262333  96.501410
3     295979   5.652474
4      50604  23.794780

In [6]:
sample_test = pd.read_csv('sample_test.csv')

In [8]:
sample_test.head(5)

,sample_id,catalog_content,image_link
0,217392,Item Name: Gift Basket Village Gourmet Meat an...,https://m.media-amazon.com/images/I/91GB1wC6Ob...
1,209156,"Item Name: NPG Dried Lotus Seeds 16 Oz, Uncook...",https://m.media-amazon.com/images/I/81VnzF1vkv...
2,262333,Item Name: Annies Homegrown Macaroni and Chees...,https://m.media-amazon.com/images/I/51aCDMHMnI...
3,295979,Item Name: Bear Creek Country Kitchens Creamy ...,https://m.media-amazon.com/images/I/71dzRyLGPi...
4,50604,Item Name: Japanese Kelp Kombu Umami Soup Stoc...,https://m.media-amazon.com/images/I/71Yu21cGwr...

In [9]:
test = pd.read_csv('test.csv')

In [10]:
test.head(5)

,sample_id,catalog_content,image_link
0,100179,Item Name: Rani 14-Spice Eshamaya's Mango Chut...,https://m.media-amazon.com/images/I/71hoAn78AW...
1,245611,Item Name: Natural MILK TEA Flavoring extract ...,https://m.media-amazon.com/images/I/61ex8NHCIj...
2,146263,Item Name: Honey Filled Hard Candy - Bulk Pack...,https://m.media-amazon.com/images/I/61KCM61J8e...
3,95658,Item Name: Vlasic Snack'mm's Kosher Dill 16 Oz...,https://m.media-amazon.com/images/I/51Ex6uOH7y...
4,36806,"Item Name: McCormick Culinary Vanilla Extract,...",https://m.media-amazon.com/images/I/71QYlrOMoS...

In [11]:
train=pd.read_csv("train.csv")

In [12]:
train.head(5)

,sample_id,catalog_content,image_link,price
0,33127,"Item Name: La Victoria Green Taco Sauce Mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89
1,198967,"Item Name: Salerno Cookies, The Original Butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12
2,261251,"Item Name: Bear Creek Hearty Soup Bowl, Creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97
3,55858,Item Name: Judee’s Blue Cheese Powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34
4,292686,"Item Name: kedem Sherry Cooking Wine, 12.7 Oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49

In [15]:
train.count()

sample_id          75000
catalog_content    75000
image_link         75000
price              75000
dtype: int64

In [17]:
test.count()

sample_id          75000
catalog_content    75000
image_link         75000
dtype: int64

In [ ]:
test.count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75000 entries, 0 to 74999
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sample_id        75000 non-null  int64
 1   catalog_content  75000 non-null  object
 2   image_link       75000 non-null  object
 3   price            75000 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 2.3+ MB

In [27]:
print(train.isnull().count())

sample_id          75000
catalog_content    75000
image_link         75000
price              75000
dtype: int64

In [28]:
test.isnull().count()

sample_id          75000
catalog_content    75000
image_link         75000
dtype: int64